replicaCount: 2
image:
  repository: ghcr.io/namdp-it/task-backend
  tag: "v1.0.0"
service:
  port: 8080
  targetPort: 8080
secretNames:
  - postgres-secret
env:
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: "taskdb_prod"
