replicaCount: 2
image:
  repository: ghcr.io/namdp-it/task-frontend
  tag: "v1.0.1"
  pullPoicy: Always
service:
  port: 80
  targetPort: 80
ingress:
  enabled: true
  host: "task-dev.test"
env:
  - name: BACKEND_URL
    value: "http://dev-backend:8080"
